services:
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    depends_on:
      - main-service
      - ai-service
    volumes:
      - ./nginx/static/:/static

  main-service:
    build: ./main-server/
    expose:
      - "8000"
    depends_on:
      - database
  second-main-service:
    build: ./main-server/
    expose:
      - "8000"
    depends_on:
      - database

  ai-service:
    build: ./ai-server/
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  metabase:
    image: metabase/metabase:latest
    depends_on:
      - database
    ports:
      - 3000:3000

networks:
  internal:
    driver: bridge
